NEWS/urls.py
from django.urls import path, include
import NEWS.views as news

app_name = 'news'
urlpatterns = [
    path('', news.MainPage.as_view(), name='main'), # основная страница
    path('news/', news.PageNews.as_view(), name='page_news'), # получение станицы со всеми новостями
    path('news/<int:id>', news.NewsInformation.as_view(), name='news_information'), # получение информации о новости
]

SITEITLAB/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from SITEITLAB import settings
app_name = 'itlab'
urlpatterns = [
    path('my/admin/', admin.site.urls),
    path('users/', include('Users.urls')),
    path('', include('NEWS.urls')),
    path('information/', include('Information_about_IT_LAB.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from .forms import LoginFormUser
import Users.views as users
from django.urls import path, reverse_lazy

from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView)
from . import views

app_name = 'users'
urlpatterns = [
    # path('login/', views.alogin()),
    path('login/', LoginView.as_view(template_name='users/login.html',
                                     authentication_form=LoginFormUser), name='login'), # переход на профиль
    path('logout/', LogoutView.as_view(), name='logout'), # выход
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('users:password_reset_done'),
        email_template_name='users/password_reset_email.html'
    ), name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('application/', views.Application.as_view(), name='application'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('profile_change/', views.ProfileChange.as_view(), name='profile_change'),
]

NEWS/models.py
from django.core.validators import FileExtensionValidator
from django.db import models

# Create your models here.

class Video(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название на английском')
    title_ru = models.CharField(max_length=100, verbose_name='Название на русском')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='image/', verbose_name='Изображение')
    file = models.FileField(
        upload_to='video/',
        validators=[FileExtensionValidator(allowed_extensions=['mp4'])],
        verbose_name='Видео'
    )
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Время обновления')

class News(models.Model):
    # title = models.CharField(max_length=100, verbose_name='Название на английском')
    title = models.CharField(max_length=100,verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    brief_description = models.CharField(max_length=100, verbose_name='Краткое описание')
    main_image = models.ImageField(upload_to='image/', verbose_name='Главное изображение')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Время обновления')
    accepted = models.BooleanField(default=False, verbose_name='Одобрено')

    def __str__(self):
        return self.title

class Galery_Image_in_News(models.Model):
    image = models.ImageField(upload_to='gallery')
    news = models.ForeignKey(News, on_delete=models.CASCADE, related_name='images')

NEWS/views.py
import requests
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.views import View
from NEWS.models import Video, News
from NEWS.asyns_news_function import get_all_news, get_news_on_main_page, get_news_information, get_galery_news_image, \
    get_user_is_authenticated, get_pagination
from asgiref.sync import sync_to_async

# Create your views here.
class MainPage(View):
    async def get(self, request):
        template_name = 'news/main.html'
        news = await get_news_on_main_page()
        is_authenticated = await get_user_is_authenticated(request)
        data = {'is_authenticated': is_authenticated, 'news': news}
        return render(request, template_name, data)

class PageNews(View):
    async def get(self, request):
        template_name = 'news/news.html'
        news = await get_all_news()
        page_obj = await get_pagination(request, news)
        is_authenticated = await get_user_is_authenticated(request)
        data = {'is_authenticated': is_authenticated, 'page_obj': page_obj}
        return render(request, template_name, data)

class NewsInformation(View):
    async def get(self, request, id):
        template_name = 'news/news_information.html'
        news = await get_news_information(id)
        galery = await get_galery_news_image(id)
        is_authenticated = await get_user_is_authenticated(request)
        data = {"news": news, 'galery': galery, 'is_authenticated': is_authenticated}
        return render(request,  template_name, data)

NEWS/templates/news/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/main.css' %}">
    <div class="application">
        <a href="{% url 'users:application' %}"> Подать заявку </a>
    </div>
    {% for new in news %}
        {% if forloop.counter < 4 %}
            <div class="content_news">
                <a href="{% url 'news:news_information' new.id %}">
                <h1 class="title">{{new.title}}</h1>
                <img src="{{new.main_image.url}}"> </img>
                <p class="news_date">{{new.time_created|date:"d.m.Y"}}</p>
                <p class="brief_description" >{{new.brief_description}}...</p>
                </a>
            </div>
        {% endif %}
    {% endfor %}

<!--        <video>-->
<!--&lt;!&ndash;             <source src="{{ video.file.url }}">&ndash;&gt;-->
<!--        </video>-->
<!--<video-->
<!--                class="video"-->
<!--                controls-->
<!--                preload="auto"-->

<!--          >-->
<!--            <source src="{{ video.file.url }}" type="video/mp4"/>-->
<!--            <source src="{{ video.file.url }}" type="video/webm"/>-->
<!--          </video>-->
</main>
{% endblock %}

NEWS/templates/news/news.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <link rel="stylesheet" href="{% static 'CSS/main.css' %}">
    {% for new in page_obj %}
            <div class="content_news">
                <a href="{% url 'news:news_information' new.id %}">
                <h1 class="title">{{new.title}}</h1>
                <img src="{{new.main_image.url}}">
                <p class="news_date">{{new.time_created|date:"d.m.Y"}}</p>
                <p class="brief_description" >{{new.brief_description}}...</p>
                </a>
            </div>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">  &laquo; </a>
                <a href="?page={{ page_obj.previous_page_number }}"> &#8249; </a>
            {% endif %}
            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}"> &#8250; </a>
                <a href="?page={{ page_obj.paginator.num_pages }}">  &raquo; </a>
            {% endif %}
        </span>
</main>
{% endblock %}

NEWS/templates/news/news_information.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
<link rel="stylesheet" href="{% static 'CSS/news_information.css' %}">
<!--    скрипт для увеличения фотографии при нажатии-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.js"></script>-->
<!--&lt;!&ndash;<script src="{% static 'js/news_information.js' %}"></script>&ndash;&gt; -->


<div class="container">
    <h1 class="title">{{news.title}}</h1>
<!--    необходимый контейнер для скрипта-->
<!--    <span class="big-photo" id="big-photo"></span>-->
    <div class="galery">
        {% for image in galery %}
          <div class="scale"><img onclick="open_photo('{{image.image.url}}')" class="photo" src="{{image.image.url}}"> </img></div>
        {% endfor %}
    </div>
    <div class="description">
        <p>{{news.description|linebreaks}}</p>
    </div>
</div>
</main>
{% endblock %}