NEWS/urls.py
from django.urls import path, include
import NEWS.views as news

app_name = 'news'
urlpatterns = [
    path('', news.MainPage.as_view(), name='main'), # основная страница
    path('news/', news.PageNews.as_view(), name='page_news'), # получение станицы со всеми новостями
    path('news/<int:id>', news.NewsInformation.as_view(), name='news_information'), # получение информации о новости
]

SITEITLAB/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from SITEITLAB import settings
app_name = 'itlab'
urlpatterns = [
    path('my/admin/', admin.site.urls),
    path('users/', include('Users.urls')),
    path('', include('NEWS.urls')),
    path('information/', include('Information_about_IT_LAB.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Users/urls.py
from .forms import LoginFormUser
import Users.views as users
from django.urls import path, reverse_lazy

from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,
                                       PasswordResetConfirmView, PasswordResetCompleteView)
from . import views

app_name = 'users'
urlpatterns = [
    # path('login/', views.alogin()),
    path('login/', LoginView.as_view(template_name='users/login.html',
                                     authentication_form=LoginFormUser), name='login'), # переход на профиль
    path('logout/', LogoutView.as_view(), name='logout'), # выход
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('users:password_reset_done'),
        email_template_name='users/password_reset_email.html'
    ), name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('application/', views.Application.as_view(), name='application'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('profile_change/', views.ProfileChange.as_view(), name='profile_change'),
]

Users/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class Secions(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    name_ru = models.CharField(max_length=50, verbose_name='Наименование на русском')

    def __str__(self):
        return self.name_ru

class ApplicationUsers(models.Model):
    group = models.CharField(max_length=20, verbose_name='Группа')
    full_name = models.CharField(max_length=100, verbose_name='ФИО')
    sections = models.ForeignKey(Secions, related_name='sections', on_delete=models.CASCADE, verbose_name='Секция')
    telegram = models.CharField(max_length = 100, verbose_name='Ваш телеграмм')
    descriptions = models.TextField(max_length = 1000,verbose_name='Информация о вас')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Время обновления')
    accepted = models.BooleanField(default=False, verbose_name='Одобрено')

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    image = models.ImageField(upload_to='imagedb/', blank=True, null=True, max_length=255,
                              validators=[FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])],
                              verbose_name='Изображение')
    quote = models.CharField(blank=True, null=True, max_length=255, verbose_name='Любимая цитата')
    group = models.CharField(verbose_name='Группа', max_length=255, blank=True, null=True)
    sections = models.ForeignKey(Secions, on_delete=models.CASCADE, verbose_name="секция",blank=True, null=True)
    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профиль пользователя'

    #автоматически создаёт профиль пользователя при регистрации
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return self.user.username

Users/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth import get_user_model
from django.forms import ModelForm

from Users.models import ApplicationUsers


class LoginFormUser(AuthenticationForm): # форма авторизации
    username = forms.CharField(label='Логин', widget=forms.TextInput())
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class ApplicationForm(ModelForm):
    def __init__(self, *args, **kwargs): # убираем у всех полей input label
        super(ModelForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.label = ''
    class Meta:
        model = ApplicationUsers
        fields = ['group', 'full_name', 'sections', 'telegram', 'descriptions']
        widgets = {
                'group': forms.TextInput(attrs={'placeholder': 'Группа'}),
                'full_name': forms.TextInput(attrs={'placeholder': 'ФИО'}),
                'telegram': forms.TextInput(attrs={'placeholder': 'Ссылка на ваш телеграм'}),
                'descriptions': forms.Textarea(attrs={'placeholder': 'Почему хотите вступить в IT лабораторию?'})
        }

# class ProfileUser(ModelForm):
#     username = forms.CharField

Users/views.py
from asgiref.sync import sync_to_async
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView

from NEWS.asyns_news_function import form_save, get_user_is_authenticated
from Users.forms import ApplicationForm
from Users.models import Profile
from django.http import JsonResponse

from Users.asyns_users_function import get_user_profile, change_profile_user, get_secions


# Create your views here.


# async def alogin(request, user, backend=None):
#
#     return await sync_to_async(login)(request, user, backend)

class ProfileUser(View):
     async def get(self, request):
        user = await request.auser()
        profile = await get_user_profile(user)
        secions = await get_secions(profile)
        is_authenticated = await get_user_is_authenticated(request)
        data = {'user': user, 'profile': profile, 'secions': secions, 'is_authenticated': is_authenticated}
        template_name = 'users/profile.html'
        return render(request, template_name, data)
class ProfileChange(View):
    async def post(self, request):
        email = request.POST.get('email')
        quote = request.POST.get('quote')
        await change_profile_user(request, email, quote)
        return JsonResponse({'message': 'Профиль изменён'})

class Application(FormView): # форма заявки
    template_name = 'users/application.html'
    form_class = ApplicationForm
    success_url = '/'
    def form_valid(self, form):
        # Сохраняем данные в базе данных асинхронно
        sync_to_async(form.save)()  # Выполняем сохранение, не ожидаем результата
        return super().form_valid(form)  # Возвращаем объект HttpResponse

    def form_invalid(self, form):
        # Возвращаем невалидную форму
        return super().form_invalid(form)  # Возвращаем объект HttpResponse

Users/templates/users/application.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'CSS/application.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
    <div class="border_application">
        <h1>Заявка в IT LAB</h1>
        <form method="POST">
                    {% csrf_token %}
            <div class="form_application">
            {{form.as_p}}
                <button id="#buttonsubmit" type="submit">Отправить</button>

               <br> <a href="{% url 'news:main' %}">Вернуться назад</a>
            </div>

        </form>
    </div>
</body>
</html>

Users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Авторизация</h1>
<div>

    <form method="post">
        {% csrf_token %}
     {{form.as_p}}

        <input type="submit" value="Войти">
        <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
    </form>

</div>
</body>
</html>

Users/templates/users/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>
</div>
</body>
</html>

Users/templates/users/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Новый пароль</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><input class="submit" type="submit" value="Сохранить"></p>

</form>
</body>
</html>

Users/templates/users/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load i18n %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
</body>
</html>

Users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

Users/templates/users/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Отправить</button>
</form>
</body>
</html>

Users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
{% csrf_token %}
<p>Hello {{user.username}}</p>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.js"></script>
<script src="{% static 'js/profile_change.js' %}"></script>
{% if user.is_staff  %}
    <a href="/my/admin/">Перейти</a>
{% endif %}
<h1>ФИО: {{user.first_name}} {{user.last_name}}</h1>
<h1>Группа: {{profile.group}} </h1>
<h1>Секция: {{secions}}</h1>
    <h1>Email: {{user.email}}</h1>
    <h1>Цитата: {{profile.quote}}</h1>
<form id="profile_change">
    {% csrf_token %}
    <input type="email" id="email" name="email" value="{{user.email}}" pattern=".+@.+\.[a-z]{2,4}$" required>
    <input type="text" id="quote" name="quote" value="{{profile.quote}}">
    <button type="submit">Изменить</button>
</form>
<!--  <input type="text" id="quote" name="quote" value="{{profile.quote}}">-->
</main>
{% endblock %}